org.gradle.configuration-cache=true
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -Dstdout.encoding=UTF-8 -Dstderr.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.fromEnv=JAVA_HOME,JDK11_HOME,JDK17_HOME,JDK21_HOME,JDK25_HOME

# Build
build.revision=1.0.0
build.profiles=java8,java11,java17,java21,java25
