<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.zero</groupId>
		<artifactId>common</artifactId>
		<version>${revision}</version>
		<relativePath>../../pom.xml</relativePath>
	</parent>

	<artifactId>common-core</artifactId>
    <packaging>jar</packaging>

    <properties>
		<aggregated.sources.dir>${project.build.directory}/aggregated-sources</aggregated.sources.dir>
		<aggregated.javadocs.dir>${project.build.directory}/aggregated-javadocs</aggregated.javadocs.dir>
    </properties>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>core-base</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
		<finalName>${project.artifactId}-${project.version}</finalName>
        <plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-sources</id>
						<phase>none</phase>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-javadocs</id>
						<phase>none</phase>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<executions>
					<execution>
						<id>shade-distribution</id>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<shadedArtifactAttached>false</shadedArtifactAttached>
							<createDependencyReducedPom>false</createDependencyReducedPom>
							<artifactSet>
								<includes>
									<include>${project.groupId}:core-base</include>
									<include>${project.groupId}:core-ip2region2</include>
									<include>${project.groupId}:core-jakarta</include>
									<include>${project.groupId}:core-spring-boot3</include>
								</includes>
							</artifactSet>
							<transformers>
								<transformer
								        implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
							</transformers>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>unpack-aggregated-sources</id>
						<phase>package</phase>
						<goals>
							<goal>unpack-dependencies</goal>
						</goals>
						<configuration>
							<includeGroupIds>${project.groupId}</includeGroupIds>
							<excludeTransitive>true</excludeTransitive>
							<includeClassifiers>sources</includeClassifiers>
							<outputDirectory>${aggregated.sources.dir}</outputDirectory>
							<markersDirectory>${project.build.directory}/dependency-markers/sources</markersDirectory>
							<excludes>META-INF/MANIFEST.MF</excludes>
						</configuration>
					</execution>
					<execution>
						<id>unpack-aggregated-javadocs</id>
						<phase>package</phase>
						<goals>
							<goal>unpack-dependencies</goal>
						</goals>
						<configuration>
							<includeGroupIds>${project.groupId}</includeGroupIds>
							<excludeTransitive>true</excludeTransitive>
							<includeClassifiers>javadoc</includeClassifiers>
							<outputDirectory>${aggregated.javadocs.dir}</outputDirectory>
							<markersDirectory>${project.build.directory}/dependency-markers/javadocs</markersDirectory>
							<excludes>META-INF/MANIFEST.MF</excludes>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-aggregated-sources</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
						<configuration>
							<finalName>${project.artifactId}-${project.version}</finalName>
							<appendAssemblyId>true</appendAssemblyId>
							<attach>true</attach>
							<descriptors>
								<descriptor>src/assembly/sources.xml</descriptor>
							</descriptors>
						</configuration>
					</execution>
					<execution>
						<id>attach-aggregated-javadocs</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
						<configuration>
							<finalName>${project.artifactId}-${project.version}</finalName>
							<appendAssemblyId>true</appendAssemblyId>
							<attach>true</attach>
							<descriptors>
								<descriptor>src/assembly/javadoc.xml</descriptor>
							</descriptors>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>com.github.github</groupId>
				<artifactId>site-maven-plugin</artifactId>
			</plugin>
        </plugins>
    </build>

	<profiles>
		<profile>
			<id>ip2region2</id>
			<dependencies>
				<dependency>
					<groupId>${project.groupId}</groupId>
					<artifactId>core-ip2region2</artifactId>
					<version>${project.version}</version>
				</dependency>
			</dependencies>
		</profile>
		<profile>
			<id>jakarta</id>
			<dependencies>
				<dependency>
					<groupId>${project.groupId}</groupId>
					<artifactId>core-jakarta</artifactId>
					<version>${project.version}</version>
				</dependency>
			</dependencies>
		</profile>
		<profile>
			<id>spring-boot3</id>
			<dependencies>
				<dependency>
					<groupId>${project.groupId}</groupId>
					<artifactId>core-jakarta</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>${project.groupId}</groupId>
					<artifactId>core-spring-boot3</artifactId>
					<version>${project.version}</version>
				</dependency>
			</dependencies>
		</profile>
	</profiles>
</project>
