[versions]
cn-dev33_sa-token-dependencies = "1.45.0"
cn-hutool_hutool-all = "5.8.40"
cn-hutool_hutool-bom = "5.8.40"
cn-idev-excel_fastexcel = "1.3.0"
com-alibaba-cloud_spring-cloud-alibaba-dependencies = "2023.0.1.0"
com-alibaba-csp_sentinel-apache-dubbo-adapter = "1.8.8"
com-alibaba-csp_sentinel-apache-dubbo3-adapter = "1.8.8"
com-alibaba-csp_sentinel-spring-webmvc-6x-adapter = "1.8.6"
com-alibaba-csp_sentinel-spring-webmvc-adapter = "1.8.8"
com-alibaba_druid-spring-boot-3-starter = "1.2.28"
com-alibaba_druid-spring-boot-starter = "1.2.28"
com-alibaba_easyexcel = "4.0.3"
com-alibaba-fastjson2_fastjson2 = "2.0.15"
com-auth0_java-jwt = "4.5.1"
com-baomidou_dynamic-datasource-spring-boot-starter = "4.5.0"
com-baomidou_dynamic-datasource-spring-boot3-starter = "4.5.8"
com-baomidou_lock4j-core = "2.2.7"
com-baomidou_lock4j-redis-template-spring-boot-starter = "2.2.7"
com-baomidou_lock4j-redisson-spring-boot-starter = "2.2.7"
com-baomidou_lock4j-zookeeper-spring-boot-starter = "2.2.7"
com-baomidou_mybatis-plus-bom = "3.5.16"
com-ctrip-framework-apollo_apollo = "2.0.1"
com-ctrip-framework-apollo_apollo-client-config-data = "2.5.0"
com-esotericsoftware_kryo = "5.6.2"
com-github-ben-manes-caffeine_caffeine = { strictly = "3.2.3" }
com-github-rholder_guava-retrying = "2.0.0"
com-github-ulisesbocchio_jasypt-spring-boot = "4.0.4"
com-github-ulisesbocchio_jasypt-spring-boot-starter = "4.0.4"
com-google-cloud_libraries-bom = "26.78.0"
com-google-code-kaptcha_kaptcha = "2.3"
com-google-code_kaptcha = "2.3.0"
com-google-protobuf_protobuf-bom = "4.32.1"
com-googlecode-juniversalchardet_juniversalchardet = "1.0.3"
com-huaweicloud_spring-cloud-huawei-bom = "1.11.12-2024.0.x"
com-lmax_disruptor = "4.0.0"
com-mybatis-flex_mybatis-flex-dependencies = "1.11.3"
com-oracle-database-jdbc_ojdbc-bom = "23.9.0.25.07"
com-querydsl_querydsl-bom = "5.1.0"
com-redis_testcontainers-redis = "2.2.4"
com-taobao-arthas_arthas-core = "4.0.5"
com-taobao-arthas_arthas-spring-boot-starter = "4.0.5"
com-xuxueli_xxl-job = "3.2.0"
com-xuxueli_xxl-job-core = "3.1.1"
io-grpc_grpc-bom = "1.75.0"
io-jsonwebtoken_jjwt-bom = "0.13.0"
io-minio_minio = "8.6.0"
io-netty_netty-bom = "4.2.6.Final"
io-projectreactor_reactor-bom = "2024.0.10"
io-swagger-core-v3_swagger-core = "2.2.35"
jakarta-platform_jakarta-jakartaee-bom = "11.0.0"
javax-inject_javax-inject = "1"
javax-servlet_servlet-api = "2.5"
log4j_log4j = "1.2.17"
net-devh_grpc-client-spring-boot-starter = "2.15.0.RELEASE"
net-devh_grpc-server-spring-boot-starter = "2.15.0.RELEASE"
org-apache-commons_commons-compress = "1.28.0"
org-apache-commons_commons-text = "1.14.0"
org-apache-dubbo_dubbo = "2.7.21"
org-apache-logging-log4j_log4j-bom = "2.24.3"
org-apache-maven_maven-model = "3.9.11"
org-apache-poi_poi-ooxml = "5.4.1"
org-apache-shardingsphere-elasticjob_elasticjob = "3.0.4"
org-apache-shardingsphere-elasticjob_elasticjob-lite-spring-boot-starter = "3.0.4"
org-apache-shiro_shiro-bom = "2.0.5"
org-dromara-dynamictp_dynamic-tp-dependencies = "1.2.2"
org-dromara-x-file-storage_x-file-storage-core = "2.3.0"
org-dromara-x-file-storage_x-file-storage-spring = "2.3.0"
org-eclipse-jetty_jetty-bom = "12.1.1"
org-jasypt_jasypt = "1.9.3"
org-jctools_jctools-core = "4.0.5"
org-jetbrains-kotlin_kotlin-bom = "2.2.20"
org-jooq_jooq-bom = "3.19.26"
org-junit_junit-bom = "5.13.4"
org-lionsoul_ip2region = "3.1.0"
org-mapstruct_mapstruct = "1.6.3"
org-mockito_mockito-bom = "5.20.0"
org-mybatis-spring-boot_mybatis-spring-boot-starter = "3.0.5"
org-mybatis_mybatis = "3.5.19"
org-mybatis_mybatis-spring = "2.1.2"
org-openjdk-jol_jol-core = "0.17"
org-owasp-encoder_encoder = "1.3.1"
org-owasp-esapi_esapi = "2.7.0.0"
org-projectlombok_lombok = "1.18.42"
org-projectlombok_lombok-mapstruct-binding = "0.2.0"
org-redisson_redisson = "3.52.0"
org-redisson_redisson-spring-boot-starter = "3.52.0"
org-slf4j_slf4j-bom = "2.0.17"
org-slf4j_slf4j-api = "2.0.17"
org-springdoc_springdoc-openapi-bom = "2.8.13"
org-springframework-boot_spring-boot-dependencies = "3.5.6"
org-springframework-cloud_spring-cloud-dependencies = "2025.0.0"
org-springframework-data_spring-data-bom = "2025.0.4"
org-springframework-integration_spring-integration-bom = "6.5.2"
org-springframework-plugin_spring-plugin = "3.0.0"
org-springframework-plugin_spring-plugin-core = "2.0.0.RELEASE"
org-springframework-plugin_spring-plugin-metadata = "2.0.0.RELEASE"
org-springframework-security_spring-security-bom = "6.5.5"
org-springframework-session_spring-session-bom = "2021.2.3"
org-springframework-shell_spring-shell-dependencies = "3.4.1"
org-springframework_spring-framework-bom = "6.2.11"
org-testcontainers_testcontainers-bom = "1.21.3"
org-zero_common-bom = "1.0.0"
tech-powerjob_powerjob-worker-spring-boot-starter = "5.1.2"
xerces_xercesImpl = "2.12.2"
org-springframework-boot = "3.1.5"

[libraries]
cn-dev33_sa-token-dependencies = { module = "cn.dev33:sa-token-dependencies", version.ref = "cn-dev33_sa-token-dependencies" }
cn-hutool_hutool-all = { module = "cn.hutool:hutool-all", version.ref = "cn-hutool_hutool-all" }
cn-hutool_hutool-bom = { module = "cn.hutool:hutool-bom", version.ref = "cn-hutool_hutool-bom" }
cn-idev-excel_fastexcel = { module = "cn.idev.excel:fastexcel", version.ref = "cn-idev-excel_fastexcel" }
com-alibaba-cloud_spring-cloud-alibaba-dependencies = { module = "com.alibaba.cloud:spring-cloud-alibaba-dependencies", version.ref = "com-alibaba-cloud_spring-cloud-alibaba-dependencies" }
com-alibaba-csp_sentinel-apache-dubbo-adapter = { module = "com.alibaba.csp:sentinel-apache-dubbo-adapter", version.ref = "com-alibaba-csp_sentinel-apache-dubbo-adapter" }
com-alibaba-csp_sentinel-apache-dubbo3-adapter = { module = "com.alibaba.csp:sentinel-apache-dubbo3-adapter", version.ref = "com-alibaba-csp_sentinel-apache-dubbo3-adapter" }
com-alibaba-csp_sentinel-spring-webmvc-6x-adapter = { module = "com.alibaba.csp:sentinel-spring-webmvc-6x-adapter", version.ref = "com-alibaba-csp_sentinel-spring-webmvc-6x-adapter" }
com-alibaba-csp_sentinel-spring-webmvc-adapter = { module = "com.alibaba.csp:sentinel-spring-webmvc-adapter", version.ref = "com-alibaba-csp_sentinel-spring-webmvc-adapter" }
com-alibaba_druid-spring-boot-3-starter = { module = "com.alibaba:druid-spring-boot-3-starter", version.ref = "com-alibaba_druid-spring-boot-3-starter" }
com-alibaba_druid-spring-boot-starter = { module = "com.alibaba:druid-spring-boot-starter", version.ref = "com-alibaba_druid-spring-boot-starter" }
com-alibaba_easyexcel = { module = "com.alibaba:easyexcel", version.ref = "com-alibaba_easyexcel" }
com-alibaba-fastjson2_fastjson2 = { module = "com.alibaba.fastjson2:fastjson2", version.ref = "com-alibaba-fastjson2_fastjson2" }
com-auth0_java-jwt = { module = "com.auth0:java-jwt", version.ref = "com-auth0_java-jwt" }
com-baomidou_dynamic-datasource-spring-boot-starter = { module = "com.baomidou:dynamic-datasource-spring-boot-starter", version.ref = "com-baomidou_dynamic-datasource-spring-boot-starter" }
com-baomidou_dynamic-datasource-spring-boot3-starter = { module = "com.baomidou:dynamic-datasource-spring-boot3-starter", version.ref = "com-baomidou_dynamic-datasource-spring-boot3-starter" }
com-baomidou_lock4j-core = { module = "com.baomidou:lock4j-core", version.ref = "com-baomidou_lock4j-core" }
com-baomidou_lock4j-redis-template-spring-boot-starter = { module = "com.baomidou:lock4j-redis-template-spring-boot-starter", version.ref = "com-baomidou_lock4j-redis-template-spring-boot-starter" }
com-baomidou_lock4j-redisson-spring-boot-starter = { module = "com.baomidou:lock4j-redisson-spring-boot-starter", version.ref = "com-baomidou_lock4j-redisson-spring-boot-starter" }
com-baomidou_lock4j-zookeeper-spring-boot-starter = { module = "com.baomidou:lock4j-zookeeper-spring-boot-starter", version.ref = "com-baomidou_lock4j-zookeeper-spring-boot-starter" }
com-baomidou_mybatis-plus-bom = { module = "com.baomidou:mybatis-plus-bom", version.ref = "com-baomidou_mybatis-plus-bom" }
com-ctrip-framework-apollo_apollo = { module = "com.ctrip.framework.apollo:apollo", version.ref = "com-ctrip-framework-apollo_apollo" }
com-ctrip-framework-apollo_apollo-client-config-data = { module = "com.ctrip.framework.apollo:apollo-client-config-data", version.ref = "com-ctrip-framework-apollo_apollo-client-config-data" }
com-esotericsoftware_kryo = { module = "com.esotericsoftware:kryo", version.ref = "com-esotericsoftware_kryo" }
com-github-ben-manes-caffeine_caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "com-github-ben-manes-caffeine_caffeine" }
com-github-rholder_guava-retrying = { module = "com.github.rholder:guava-retrying", version.ref = "com-github-rholder_guava-retrying" }
com-github-ulisesbocchio_jasypt-spring-boot = { module = "com.github.ulisesbocchio:jasypt-spring-boot", version.ref = "com-github-ulisesbocchio_jasypt-spring-boot" }
com-github-ulisesbocchio_jasypt-spring-boot-starter = { module = "com.github.ulisesbocchio:jasypt-spring-boot-starter", version.ref = "com-github-ulisesbocchio_jasypt-spring-boot-starter" }
com-google-cloud_libraries-bom = { module = "com.google.cloud:libraries-bom", version.ref = "com-google-cloud_libraries-bom" }
com-google-code-kaptcha_kaptcha = { module = "com.google.code.kaptcha:kaptcha", version.ref = "com-google-code-kaptcha_kaptcha" }
com-google-code_kaptcha = { module = "com.google.code:kaptcha", version.ref = "com-google-code_kaptcha" }
com-google-protobuf_protobuf-bom = { module = "com.google.protobuf:protobuf-bom", version.ref = "com-google-protobuf_protobuf-bom" }
com-googlecode-juniversalchardet_juniversalchardet = { module = "com.googlecode.juniversalchardet:juniversalchardet", version.ref = "com-googlecode-juniversalchardet_juniversalchardet" }
com-huaweicloud_spring-cloud-huawei-bom = { module = "com.huaweicloud:spring-cloud-huawei-bom", version.ref = "com-huaweicloud_spring-cloud-huawei-bom" }
com-lmax_disruptor = { module = "com.lmax:disruptor", version.ref = "com-lmax_disruptor" }
com-mybatis-flex_mybatis-flex-dependencies = { module = "com.mybatis-flex:mybatis-flex-dependencies", version.ref = "com-mybatis-flex_mybatis-flex-dependencies" }
com-oracle-database-jdbc_ojdbc-bom = { module = "com.oracle.database.jdbc:ojdbc-bom", version.ref = "com-oracle-database-jdbc_ojdbc-bom" }
com-querydsl_querydsl-bom = { module = "com.querydsl:querydsl-bom", version.ref = "com-querydsl_querydsl-bom" }
com-redis_testcontainers-redis = { module = "com.redis:testcontainers-redis", version.ref = "com-redis_testcontainers-redis" }
com-taobao-arthas_arthas-core = { module = "com.taobao.arthas:arthas-core", version.ref = "com-taobao-arthas_arthas-core" }
com-taobao-arthas_arthas-spring-boot-starter = { module = "com.taobao.arthas:arthas-spring-boot-starter", version.ref = "com-taobao-arthas_arthas-spring-boot-starter" }
com-xuxueli_xxl-job = { module = "com.xuxueli:xxl-job", version.ref = "com-xuxueli_xxl-job" }
com-xuxueli_xxl-job-core = { module = "com.xuxueli:xxl-job-core", version.ref = "com-xuxueli_xxl-job-core" }
io-grpc_grpc-bom = { module = "io.grpc:grpc-bom", version.ref = "io-grpc_grpc-bom" }
io-jsonwebtoken_jjwt-bom = { module = "io.jsonwebtoken:jjwt-bom", version.ref = "io-jsonwebtoken_jjwt-bom" }
io-minio_minio = { module = "io.minio:minio", version.ref = "io-minio_minio" }
io-netty_netty-bom = { module = "io.netty:netty-bom", version.ref = "io-netty_netty-bom" }
io-projectreactor_reactor-bom = { module = "io.projectreactor:reactor-bom", version.ref = "io-projectreactor_reactor-bom" }
io-swagger-core-v3_swagger-core = { module = "io.swagger.core.v3:swagger-core", version.ref = "io-swagger-core-v3_swagger-core" }
jakarta-platform_jakarta-jakartaee-bom = { module = "jakarta.platform:jakarta.jakartaee-bom", version.ref = "jakarta-platform_jakarta-jakartaee-bom" }
javax-inject_javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject_javax-inject" }
javax-servlet_servlet-api = { module = "javax.servlet:servlet-api", version.ref = "javax-servlet_servlet-api" }
log4j_log4j = { module = "log4j:log4j", version.ref = "log4j_log4j" }
net-devh_grpc-client-spring-boot-starter = { module = "net.devh:grpc-client-spring-boot-starter", version.ref = "net-devh_grpc-client-spring-boot-starter" }
net-devh_grpc-server-spring-boot-starter = { module = "net.devh:grpc-server-spring-boot-starter", version.ref = "net-devh_grpc-server-spring-boot-starter" }
org-apache-commons_commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "org-apache-commons_commons-compress" }
org-apache-commons_commons-text = { module = "org.apache.commons:commons-text", version.ref = "org-apache-commons_commons-text" }
org-apache-dubbo_dubbo = { module = "org.apache.dubbo:dubbo", version.ref = "org-apache-dubbo_dubbo" }
org-apache-logging-log4j_log4j-bom = { module = "org.apache.logging.log4j:log4j-bom", version.ref = "org-apache-logging-log4j_log4j-bom" }
org-apache-maven_maven-model = { module = "org.apache.maven:maven-model", version.ref = "org-apache-maven_maven-model" }
org-apache-poi_poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "org-apache-poi_poi-ooxml" }
org-apache-shardingsphere-elasticjob_elasticjob = { module = "org.apache.shardingsphere.elasticjob:elasticjob", version.ref = "org-apache-shardingsphere-elasticjob_elasticjob" }
org-apache-shardingsphere-elasticjob_elasticjob-lite-spring-boot-starter = { module = "org.apache.shardingsphere.elasticjob:elasticjob-lite-spring-boot-starter", version.ref = "org-apache-shardingsphere-elasticjob_elasticjob-lite-spring-boot-starter" }
org-apache-shiro_shiro-bom = { module = "org.apache.shiro:shiro-bom", version.ref = "org-apache-shiro_shiro-bom" }
org-dromara-dynamictp_dynamic-tp-dependencies = { module = "org.dromara.dynamictp:dynamic-tp-dependencies", version.ref = "org-dromara-dynamictp_dynamic-tp-dependencies" }
org-dromara-x-file-storage_x-file-storage-core = { module = "org.dromara.x-file-storage:x-file-storage-core", version.ref = "org-dromara-x-file-storage_x-file-storage-core" }
org-dromara-x-file-storage_x-file-storage-spring = { module = "org.dromara.x-file-storage:x-file-storage-spring", version.ref = "org-dromara-x-file-storage_x-file-storage-spring" }
org-eclipse-jetty_jetty-bom = { module = "org.eclipse.jetty:jetty-bom", version.ref = "org-eclipse-jetty_jetty-bom" }
org-jasypt_jasypt = { module = "org.jasypt:jasypt", version.ref = "org-jasypt_jasypt" }
org-jctools_jctools-core = { module = "org.jctools:jctools-core", version.ref = "org-jctools_jctools-core" }
org-jetbrains-kotlin_kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "org-jetbrains-kotlin_kotlin-bom" }
org-jooq_jooq-bom = { module = "org.jooq:jooq-bom", version.ref = "org-jooq_jooq-bom" }
org-junit_junit-bom = { module = "org.junit:junit-bom", version.ref = "org-junit_junit-bom" }
org-lionsoul_ip2region = { module = "org.lionsoul:ip2region", version.ref = "org-lionsoul_ip2region" }
org-mapstruct_mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "org-mapstruct_mapstruct" }
org-mockito_mockito-bom = { module = "org.mockito:mockito-bom", version.ref = "org-mockito_mockito-bom" }
org-mybatis-spring-boot_mybatis-spring-boot-starter = { module = "org.mybatis.spring.boot:mybatis-spring-boot-starter", version.ref = "org-mybatis-spring-boot_mybatis-spring-boot-starter" }
org-mybatis_mybatis = { module = "org.mybatis:mybatis", version.ref = "org-mybatis_mybatis" }
org-mybatis_mybatis-spring = { module = "org.mybatis:mybatis-spring", version.ref = "org-mybatis_mybatis-spring" }
org-openjdk-jol_jol-core = { module = "org.openjdk.jol:jol-core", version.ref = "org-openjdk-jol_jol-core" }
org-owasp-encoder_encoder = { module = "org.owasp.encoder:encoder", version.ref = "org-owasp-encoder_encoder" }
org-owasp-esapi_esapi = { module = "org.owasp.esapi:esapi", version.ref = "org-owasp-esapi_esapi" }
org-projectlombok_lombok = { module = "org.projectlombok:lombok", version.ref = "org-projectlombok_lombok" }
org-projectlombok_lombok-mapstruct-binding = { module = "org.projectlombok:lombok-mapstruct-binding", version.ref = "org-projectlombok_lombok-mapstruct-binding" }
org-redisson_redisson = { module = "org.redisson:redisson", version.ref = "org-redisson_redisson" }
org-redisson_redisson-spring-boot-starter = { module = "org.redisson:redisson-spring-boot-starter", version.ref = "org-redisson_redisson-spring-boot-starter" }
org-slf4j_slf4j-bom = { module = "org.slf4j:slf4j-bom", version.ref = "org-slf4j_slf4j-bom" }
org-slf4j_slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "org-slf4j_slf4j-api" }
org-springdoc_springdoc-openapi-bom = { module = "org.springdoc:springdoc-openapi-bom", version.ref = "org-springdoc_springdoc-openapi-bom" }
org-springframework-boot_spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "org-springframework-boot_spring-boot-dependencies" }
org-springframework-cloud_spring-cloud-dependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "org-springframework-cloud_spring-cloud-dependencies" }
org-springframework-data_spring-data-bom = { module = "org.springframework.data:spring-data-bom", version.ref = "org-springframework-data_spring-data-bom" }
org-springframework-integration_spring-integration-bom = { module = "org.springframework.integration:spring-integration-bom", version.ref = "org-springframework-integration_spring-integration-bom" }
org-springframework-plugin_spring-plugin = { module = "org.springframework.plugin:spring-plugin", version.ref = "org-springframework-plugin_spring-plugin" }
org-springframework-plugin_spring-plugin-core = { module = "org.springframework.plugin:spring-plugin-core", version.ref = "org-springframework-plugin_spring-plugin-core" }
org-springframework-plugin_spring-plugin-metadata = { module = "org.springframework.plugin:spring-plugin-metadata", version.ref = "org-springframework-plugin_spring-plugin-metadata" }
org-springframework-security_spring-security-bom = { module = "org.springframework.security:spring-security-bom", version.ref = "org-springframework-security_spring-security-bom" }
org-springframework-session_spring-session-bom = { module = "org.springframework.session:spring-session-bom", version.ref = "org-springframework-session_spring-session-bom" }
org-springframework-shell_spring-shell-dependencies = { module = "org.springframework.shell:spring-shell-dependencies", version.ref = "org-springframework-shell_spring-shell-dependencies" }
org-springframework_spring-framework-bom = { module = "org.springframework:spring-framework-bom", version.ref = "org-springframework_spring-framework-bom" }
org-testcontainers_testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "org-testcontainers_testcontainers-bom" }
org-zero_common-bom = { module = "org.zero:common-bom", version.ref = "org-zero_common-bom" }
tech-powerjob_powerjob-worker-spring-boot-starter = { module = "tech.powerjob:powerjob-worker-spring-boot-starter", version.ref = "tech-powerjob_powerjob-worker-spring-boot-starter" }
xerces_xercesImpl = { module = "xerces:xercesImpl", version.ref = "xerces_xercesImpl" }

[bundles]

[plugins]
org-springframework-boot = { id = "org.springframework.boot", version.ref = "org-springframework-boot" }

