[versions]
# ************************************ Artifact ************************************
revison = "1.0.0"
# 目前 Gradle libs.versions.toml 还无法做到像 Maven pom.xml 一样，可以在属性中引用另一个属性（变量插值）
# org-zero_common-bom = {ref = "revison"}
org-zero_common-bom = "1.0.0"
# Java
org-openjdk-jmh_jmh-core = "1.37"
org-openjdk-jol_jol-core = "0.17"
# Apache
org-apache-commons_commons-text = "1.11.0"
org-apache-commons_commons-compress = "1.26.1"
org-apache-poi_poi-ooxml = "5.2.5"
org-apache-shiro_shiro-bom = "2.0.5"
org-apache-dubbo_dubbo-bom = "3.2.12"
org-apache-logging-log4j_log4j-bom = "2.24.3"
org-apache-shardingsphere-elasticjob_elasticjob = "3.0.4"
org-apache-shardingsphere-elasticjob_elasticjob-lite-spring-boot-starter = "3.0.4"
# Spring
# The latest version supported by JDK 8
org-springframework_spring-framework-bom = "5.3.39"
# The latest version supported by JDK 8
org-springframework-boot_spring-boot-dependencies = "2.7.18"
# The latest version supported by JDK 8
org-springframework-cloud_spring-cloud-dependencies = "2021.0.9"
org-springframework-shell_spring-shell-dependencies = "2.1.7"
org-springframework-data_spring-data-bom = "2021.2.17"
org-springframework-integration_spring-integration-bom = "5.5.19"
org-springframework-security_spring-security-bom = "5.7.11"
org-springframework-session_spring-session-bom = "2021.2.3"
org-springframework-plugin_spring-plugin-core = "2.0.0.RELEASE"
org-springframework-plugin_spring-plugin-metadata = "2.0.0.RELEASE"
# Eclipse
org-eclipse-jetty_jetty-bom = "12.0.19"
jakarta-platform_jakarta-jakartaee-bom = "11.0.0"
jakarta-xml-bind_jakarta-xml-bind-api = "4.0.2"
com-sun-xml-bind_jaxb-impl = "4.0.5"
# Google
com-google-cloud_libraries-bom = "26.59.0"
com-google-guava_guava = "31.1-jre"
com-google-code-gson_gson = "2.10.1"
com-google-protobuf_protobuf-bom = "4.31.1"
com-googlecode-juniversalchardet_juniversalchardet = "1.0.3"
# Alibaba
# The latest version supported by JDK 8
com-alibaba-cloud_spring-cloud-alibaba-dependencies = "2021.0.6.0"
com-alibaba_easyexcel = "4.0.3"
com-alibaba-csp_sentinel-apache-dubbo-adapter = "1.8.6"
com-alibaba-csp_sentinel-apache-dubbo3-adapter = "1.8.6"
com-alibaba_druid = "1.2.27"
com-alibaba_druid-spring-boot-starter = "1.2.27"
com-alibaba_fastjson = "1.2.83"
com-alibaba-fastjson2_fastjson2 = "2.0.58"
com-alibaba_transmittable-thread-local = "2.14.2"
com-alicp-jetcache_jetcache-core = "2.7.3"
com-alicp-jetcache_jetcache-starter-redis = "2.7.3"
com-alicp-jetcache_jetcache-starter-redis-lettuce = "2.7.3"
com-alicp-jetcache_jetcache-starter-redisson = "2.7.3"
com-taobao-arthas_arthas-core = "3.4.8"
com-taobao-arthas_arthas-spring-boot-starter = "3.4.8"
# Huawei
# The latest version supported by JDK 8
com-huaweicloud_spring-cloud-huawei-bom = "1.11.10-2021.0.x"
# Github
com-github-penggle_kaptcha = "2.3.2"
com-github-rholder_guava-retrying = "2.0.0"
com-github-ulisesbocchio_jasypt-spring-boot = "3.0.5"
com-github-ulisesbocchio_jasypt-spring-boot-starter = "3.0.5"
# Dromara
org-dromara-dynamictp_dynamic-tp-core = "1.2.2"
org-dromara-dynamictp_dynamic-tp-dependencies = "1.2.2"
org-dromara-x-file-storage_x-file-storage-spring = "2.3.0"
cn-dev33_sa-token-core = "1.44.0"
cn-dev33_sa-token-spring-boot-starter = "1.44.0"
cn-hutool_hutool-all = "5.8.39"
cn-hutool_hutool-bom = "5.8.39"

# Other
com-mysql_mysql-connector-j = "8.0.32"
com-redis_testcontainers-redis = "2.2.4"
com-mybatis-flex_mybatis-flex-dependencies = "1.11.0"
com-baomidou_mybatis-plus = "3.5.12"
com-baomidou_mybatis-plus-bom = "3.5.12"
com-baomidou_mybatis-plus-generator = "3.5.12"
com-baomidou_dynamic-datasource-spring-boot-starter = "4.2.0"
com-baomidou_lock4j-core = "2.2.7"
com-baomidou_lock4j-redisson-spring-boot-starter = "2.2.7"
com-baomidou_lock4j-redis-template-spring-boot-starter = "2.2.7"
com-baomidou_lock4j-zookeeper-spring-boot-starter = "2.2.7"
com-xuxueli_xxl-job-core = "3.1.1"
com-ctrip-framework-apollo_apollo-core = "2.4.0"
com-ctrip-framework-apollo_apollo-client-config-data = "2.4.0"
com-lmax_disruptor = "3.4.4"
com-esotericsoftware_kryo = "5.2.1"
com-querydsl_querydsl-bom = "5.1.0"
com-auth0_java-jwt = "4.5.0"
org-lionsoul_ip2region = "2.7.0"
org-owasp-esapi_esapi = "2.6.2.0"
org-owasp-encoder_encoder = "1.3.1"
org-jooq_jooq = "3.19.24"
org-liquibase_liquibase-core = "4.31.1"
org-jetbrains-kotlin_kotlin-stdlib = "1.9.25"
org-flywaydb_flyway-core = "11.7.2"
org-testcontainers_testcontainers-bom = "1.21.2"
org-mybatis_mybatis = "3.5.19"
org-mybatis_mybatis-spring = "2.1.2"
org-mybatis-spring-boot_mybatis-spring-boot-starter = "2.3.2"
org-redisson_redisson = "3.27.2"
org-jasypt_jasypt = "1.9.3"
org-projectlombok_lombok = "1.18.38"
org-projectlombok_lombok-mapstruct-binding = "0.2.0"
org-mapstruct_mapstruct = "1.6.3"
org-slf4j_slf4j-bom = "2.0.17"
org-junit_junit-bom = "5.10.3"
org-mockito-mockito-bom = "5.18.0"
org-springdoc_springdoc-openapi-bom = "2.8.9"
org-jctools_jctools-core = "4.0.5"
io-minio_minio = "8.5.2"
io-swagger-core-v3_swagger-core = "2.2.35"
io-grpc_grpc-core = "1.74.0"
io-projectreactor_reactor-bom = "2024.0.7"
io-netty_netty-bom = "4.1.116.Final"
io-jsonwebtoken_jjwt-api = "0.12.6"
io-jsonwebtoken_jjwt-impl = "0.12.6"
io-jsonwebtoken_jjwt-jackson = "0.12.6"
io-jsonwebtoken_jjwt-gson = "0.12.6"
io-jsonwebtoken_jjwt-orgjson = "0.12.6"
net-devh_grpc-spring-boot-starter = "3.1.0.RELEASE"
net-devh_grpc-server-spring-boot-starter = "3.1.0.RELEASE"
net-devh_grpc-client-spring-boot-starter = "3.1.0.RELEASE"
cn-idev-excel_fastexcel = "1.0.0"
tech-powerjob_powerjob-worker-spring-boot-starter = "5.1.1"
xerces_xercesImpl = "2.12.2"

# ************************************ Plugin ************************************
# Maven
org-apache-maven-plugins_maven-clean-plugin = "3.5.0"
org-apache-maven-plugins_maven-compiler-plugin = "3.14.0"
org-apache-maven-plugins_maven-source-plugin = "3.3.1"
org-apache-maven-plugins_maven-resources-plugin = "3.3.1"
org-apache-maven-plugins_maven-dependency-plugin = "3.8.1"
org-apache-maven-plugins_maven-javadoc-plugin = "3.11.2"
org-apache-maven-plugins_maven-jar-plugin = "3.3.0"
org-apache-maven-plugins_maven-war-plugin = "3.4.0"
org-apache-maven-plugins_maven-shade-plugin = "3.6.0"
org-apache-maven-plugins_maven-assembly-plugin = "3.7.1"
org-apache-maven-plugins_maven-wrapper-plugin = "3.3.2"
org-apache-maven-plugins_maven-install-plugin = "3.1.4"
org-apache-maven-plugins_maven-antrun-plugin = "3.1.0"
org-apache-maven-plugins_maven-deploy-plugin = "3.1.4"
org-apache-maven-plugins_maven-enforcer-plugin = "3.5.0"
org-apache-maven-plugins_maven-failsafe-plugin = "3.5.3"
org-apache-maven-plugins_maven-help-plugin = "3.5.1"
org-apache-maven-plugins_maven-invoker-plugin = "3.9.0"
org-apache-maven-plugins_maven-surefire-plugin = "3.5.3"
org-apache-maven-plugins_maven-gpg-plugin = "3.2.8"
# Spring
org-springframework-boot_spring-boot-maven-plugin = "2.7.18"
# Codehaus
org-codehaus-mojo_build-helper-maven-plugin = "3.6.1"
org-codehaus-mojo_versions-maven-plugin = "2.18.0"
org-codehaus-mojo_xml-maven-plugin = "1.1.0"
# Github
com-github-github_site-maven-plugin = "0.12"
io-github-git-commit-id_git-commit-id-maven-plugin = "9.0.2"
# Other
org-cyclonedx_cyclonedx-maven-plugin = "2.9.1"
org-flywaydb_flyway-maven-plugin = "11.7.2"
org-jooq_jooq-codegen-maven = "3.19.24"
org-jetbrains-kotlin_kotlin-maven-plugin = "1.9.25"
org-liquibase_liquibase-maven-plugin = "4.31.1"
org-graalvm-buildtools_native-maven-plugin = "0.10.6"

[libraries]
org-zero_common-bom = {module = "org.zero:common-bom", version.ref = "org-zero_common-bom"}
# Java
org-openjdk-jol_jol-core = {module = "org.openjdk.jol:jol-core", version.ref = "org-openjdk-jol_jol-core"}
org-openjdk-jmh_jmh-core = {module = "org.openjdk.jmh:jmh-core", version.ref = "org-openjdk-jmh_jmh-core"}
org-openjdk-jmh_jmh-generator-annprocess = {module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "org-openjdk-jmh_jmh-core"}
javax-servlet_servlet-api = {module = "javax.servlet:servlet-api", version = "2.5"}
javax-servlet_javax-servlet-api = {module = "javax.servlet:javax.servlet-api", version = "4.0.1"}
javax-inject_javax-inject = {module = "javax.inject:javax.inject", version = "1"}
javax-xml-bind_jaxb-api = {module = "javax.xml.bind:jaxb-api", version = "2.3.1"}
# Apache
org-apache-dubbo_dubbo-bom = {module = "org.apache.dubbo:dubbo-bom", version.ref = "org-apache-dubbo_dubbo-bom"}
org-apache-shiro_shiro-bom = {module = "org.apache.shiro:shiro-bom", version.ref = "org-apache-shiro_shiro-bom"}
org-apache-logging-log4j_log4j-bom = {module = "org.apache.logging.log4j:log4j-bom", version.ref = "org-apache-logging-log4j_log4j-bom"}
log4j_log4j = {module = "log4j:log4j", version = "1.2.17"}
org-apache-poi_poi-ooxml = {module = "org.apache.poi:poi-ooxml", version.ref = "org-apache-poi_poi-ooxml"}
org-apache-commons_commons-text = {module = "org.apache.commons:commons-text", version.ref = "org-apache-commons_commons-text"}
org-apache-commons_commons-compress = {module = "org.apache.commons:commons-compress", version.ref = "org-apache-commons_commons-compress"}
# Spring
org-springframework_spring-framework-bom = {module = "org.springframework:spring-framework-bom", version.ref = "org-springframework_spring-framework-bom"}
org-springframework-boot_spring-boot-dependencies = {module = "org.springframework.boot:spring-boot-dependencies", version.ref = "org-springframework-boot_spring-boot-dependencies"}
org-springframework-cloud_spring-cloud-dependencies = {module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "org-springframework-cloud_spring-cloud-dependencies"}
org-springframework-data_spring-data-bom = {module = "org.springframework.data:spring-data-bom", version.ref = "org-springframework-data_spring-data-bom"}
org-springframework-security_spring-security-bom = {module = "org.springframework.security:spring-security-bom", version.ref = "org-springframework-security_spring-security-bom"}
org-springframework-integration_spring-integration-bom = {module = "org.springframework.integration:spring-integration-bom", version.ref = "org-springframework-integration_spring-integration-bom"}
org-springframework-shell_spring-shell-dependencies = {module = "org.springframework.shell:spring-shell-dependencies", version.ref = "org-springframework-shell_spring-shell-dependencies"}
org-springframework-session_spring-session-bom = {module = "org.springframework.session:spring-session-bom", version.ref = "org-springframework-session_spring-session-bom"}
org-springframework-plugin_spring-plugin-core = {module = "org.springframework.plugin:spring-plugin-core", version.ref = "org-springframework-plugin_spring-plugin-core"}
org-springframework-plugin_spring-plugin-metadata = {module = "org.springframework.plugin:spring-plugin-metadata", version.ref = "org-springframework-plugin_spring-plugin-metadata"}
# Eclipse
jakarta-platform_jakarta-jakartaee-bom = {module = "jakarta.platform:jakarta.jakartaee-bom", version.ref = "jakarta-platform_jakarta-jakartaee-bom"}
jakarta-xml-bind_jakarta-xml-bind-api = {module = "jakarta.xml.bind:jakarta.xml.bind-api", version.ref = "jakarta-xml-bind_jakarta-xml-bind-api"}
com-sun-xml-bind_jaxb-impl = {module = "com.sun.xml.bind:jaxb-impl", version.ref = "com-sun-xml-bind_jaxb-impl"}
org-eclipse-jetty_jetty-bom = {module = "org.eclipse.jetty:jetty-bom", version.ref = "org-eclipse-jetty_jetty-bom"}
# Google
com-google-cloud_libraries-bom = {module = "com.google.cloud:libraries-bom", version.ref = "com-google-cloud_libraries-bom"}
com-google-guava_guava = {module = "com.google.guava:guava", version.ref = "com-google-guava_guava"}
com-google-code-gson_gson = {module = "com.google.code.gson:gson", version.ref = "com-google-code-gson_gson"}
com-google-protobuf_protobuf-bom = {module = "com.google.protobuf:protobuf-bom", version = "4.31.1"}
com-googlecode-juniversalchardet_juniversalchardet = {module = "com.googlecode.juniversalchardet:juniversalchardet", version.ref = "com-googlecode-juniversalchardet_juniversalchardet"}
# Alibaba
com-alibaba_easyexcel = {module = "com.alibaba:easyexcel", version.ref = "com-alibaba_easyexcel"}
com-alibaba_transmittable-thread-local = {module = "com.alibaba:transmittable-thread-local", version.ref = "com-alibaba_transmittable-thread-local"}
com-alibaba-cloud_spring-cloud-alibaba-dependencies = {module = "com.alibaba.cloud:spring-cloud-alibaba-dependencies", version.ref = "com-alibaba-cloud_spring-cloud-alibaba-dependencies"}
com-alibaba-csp_sentinel-apache-dubbo-adapter = {module = "com.alibaba.csp:sentinel-apache-dubbo-adapter", version.ref = "com-alibaba-csp_sentinel-apache-dubbo-adapter"}
com-alibaba-csp_sentinel-apache-dubbo3-adapter = {module = "com.alibaba.csp:sentinel-apache-dubbo3-adapter", version.ref = "com-alibaba-csp_sentinel-apache-dubbo3-adapter"}
# Huawei
com-huaweicloud_spring-cloud-huawei-bom = {module = "com.huaweicloud:spring-cloud-huawei-bom", version.ref = "com-huaweicloud_spring-cloud-huawei-bom"}
# Github
com-github-rholder_guava-retrying = {module = "com.github.rholder:guava-retrying", version.ref = "com-github-rholder_guava-retrying"}
com-github-ulisesbocchio_jasypt-spring-boot = {module = "com.github.ulisesbocchio:jasypt-spring-boot", version.ref = "com-github-ulisesbocchio_jasypt-spring-boot"}
com-github-ulisesbocchio_jasypt-spring-boot-starter = {module = "com.github.ulisesbocchio:jasypt-spring-boot-starter", version.ref = "com-github-ulisesbocchio_jasypt-spring-boot-starter"}
# Dromara
org-dromara-dynamictp_dynamic-tp-dependencies = {module = "org.dromara.dynamictp:dynamic-tp-dependencies", version.ref = "org-dromara-dynamictp_dynamic-tp-dependencies"}
cn-hutool_hutool-bom = {module = "cn.hutool:hutool-bom", version.ref = "cn-hutool_hutool-bom"}
cn-hutool_hutool-all = {module = "cn.hutool:hutool-all", version.ref = "cn-hutool_hutool-all"}
# Other
org-projectlombok_lombok = {module = "org.projectlombok:lombok", version.ref = "org-projectlombok_lombok"}
io-projectreactor_reactor-bom = {module = "io.projectreactor:reactor-bom", version.ref = "io-projectreactor_reactor-bom"}
io-netty_netty-bom = {module = "io.netty:netty-bom", version.ref = "io-netty_netty-bom"}
org-slf4j_slf4j-bom = {module = "org.slf4j:slf4j-bom", version.ref = "org-slf4j_slf4j-bom"}
org-junit_junit-bom = {module = "org.junit:junit-bom", version.ref = "org-junit_junit-bom"}
org-testcontainers_testcontainers-bom = {module = "org.testcontainers:testcontainers-bom", version.ref = "org-testcontainers_testcontainers-bom"}
org-mybatis-spring-boot_mybatis-spring-boot-starter = {module = "org.mybatis.spring.boot:mybatis-spring-boot-starter", version.ref = "org-mybatis-spring-boot_mybatis-spring-boot-starter"}
org-mockito-mockito-bom = {module = "org.mockito:mockito-bom", version.ref = "org-mockito-mockito-bom"}
com-querydsl_querydsl-bom = {module = "com.querydsl:querydsl-bom", version.ref = "com-querydsl_querydsl-bom"}
com-baomidou_mybatis-plus-bom = {module = "com.baomidou:mybatis-plus-bom", version.ref = "com-baomidou_mybatis-plus-bom"}
com-mybatis-flex_mybatis-flex-dependencies = {module = "com.mybatis-flex:mybatis-flex-dependencies", version.ref = "com-mybatis-flex_mybatis-flex-dependencies"}
cn-idev-excel_fastexcel = {module = "cn.idev.excel:fastexcel", version.ref = "cn-idev-excel_fastexcel"}
io-minio_minio = {module = "io.minio:minio", version.ref = "io-minio_minio"}
xerces_xercesImpl = {module = "xerces:xercesImpl", version.ref = "xerces_xercesImpl"}
org-redisson_redisson = {module = "org.redisson:redisson", version.ref = "org-redisson_redisson"}
org-jctools_jctools-core = {module = "org.jctools:jctools-core", version.ref = "org-jctools_jctools-core"}
com-lmax_disruptor = {module = "com.lmax:disruptor", version.ref = "com-lmax_disruptor"}
com-esotericsoftware_kryo = {module = "com.esotericsoftware:kryo", version.ref = "com-esotericsoftware_kryo"}
org-lionsoul_ip2region = {module = "org.lionsoul:ip2region", version.ref = "org-lionsoul_ip2region"}
org-jasypt_jasypt = {module = "org.jasypt:jasypt", version.ref = "org-jasypt_jasypt"}
org-owasp-esapi_esapi = {module = "org.owasp.esapi:esapi", version.ref = "org-owasp-esapi_esapi"}
org-owasp-encoder_encoder = {module = "org.owasp.encoder:encoder", version.ref = "org-owasp-encoder_encoder"}
io-jsonwebtoken_jjwt-api = {module = "io.jsonwebtoken:jjwt-api", version.ref = "io-jsonwebtoken_jjwt-api"}
io-jsonwebtoken_jjwt-impl = {module = "io.jsonwebtoken:jjwt-impl", version.ref = "io-jsonwebtoken_jjwt-impl"}
io-jsonwebtoken_jjwt-jackson = {module = "io.jsonwebtoken:jjwt-jackson", version.ref = "io-jsonwebtoken_jjwt-jackson"}
io-jsonwebtoken_jjwt-gson = {module = "io.jsonwebtoken:jjwt-gson", version.ref = "io-jsonwebtoken_jjwt-gson"}
io-jsonwebtoken_jjwt-orgjson = {module = "io.jsonwebtoken:jjwt-orgjson", version.ref = "io-jsonwebtoken_jjwt-orgjson"}
com-auth0_java-jwt = {module = "com.auth0:java-jwt", version.ref = "com-auth0_java-jwt"}

[bundles]

[plugins]
# Gradle
org-gradle-wrapper-upgrade = "org.gradle.wrapper-upgrade:0.12"
# Maven
org-apache-maven-plugins_maven-clean-plugin = {id = "org.apache.maven.plugins.maven-clean-plugin", version.ref = "org-apache-maven-plugins_maven-clean-plugin"}
org-apache-maven-plugins_maven-compiler-plugin = {id = "org.apache.maven.plugins.maven-compiler-plugin", version.ref = "org-apache-maven-plugins_maven-compiler-plugin"}
org-apache-maven-plugins_maven-source-plugin = {id = "org.apache.maven.plugins.maven-source-plugin", version.ref = "org-apache-maven-plugins_maven-source-plugin"}
org-apache-maven-plugins_maven-javadoc-plugin = {id = "org.apache.maven.plugins.maven-javadoc-plugin", version.ref = "org-apache-maven-plugins_maven-javadoc-plugin"}
org-apache-maven-plugins_maven-dependency-plugin = {id = "org.apache.maven.plugins.maven-dependency-plugin", version.ref = "org-apache-maven-plugins_maven-dependency-plugin"}
org-apache-maven-plugins_maven-resources-plugin = {id = "org.apache.maven.plugins.maven-resources-plugin", version.ref = "org-apache-maven-plugins_maven-resources-plugin"}
org-apache-maven-plugins_maven-jar-plugin = {id = "org.apache.maven.plugins.maven-jar-plugin", version.ref = "org-apache-maven-plugins_maven-jar-plugin"}
org-apache-maven-plugins_maven-war-plugin = {id = "org.apache.maven.plugins.maven-war-plugin", version.ref = "org-apache-maven-plugins_maven-war-plugin"}
org-apache-maven-plugins_maven-shade-plugin = {id = "org.apache.maven.plugins.maven-shade-plugin", version.ref = "org-apache-maven-plugins_maven-shade-plugin"}
org-apache-maven-plugins_maven-assembly-plugin = {id = "org.apache.maven.plugins.maven-assembly-plugin", version.ref = "org-apache-maven-plugins_maven-assembly-plugin"}
org-apache-maven-plugins_maven-wrapper-plugin = {id = "org.apache.maven.plugins.maven-wrapper-plugin", version.ref = "org-apache-maven-plugins_maven-wrapper-plugin"}
org-apache-maven-plugins_maven-antrun-plugin = {id = "org.apache.maven.plugins.maven-antrun-plugin", version.ref = "org-apache-maven-plugins_maven-antrun-plugin"}
org-apache-maven-plugins_maven-deploy-plugin = {id = "org.apache.maven.plugins.maven-deploy-plugin", version.ref = "org-apache-maven-plugins_maven-deploy-plugin"}
org-apache-maven-plugins_maven-enforcer-plugin = {id = "org.apache.maven.plugins.maven-enforcer-plugin", version.ref = "org-apache-maven-plugins_maven-enforcer-plugin"}
org-apache-maven-plugins_maven-surefire-plugin = {id = "org.apache.maven.plugins.maven-surefire-plugin", version.ref = "org-apache-maven-plugins_maven-surefire-plugin"}
org-apache-maven-plugins_maven-failsafe-plugin = {id = "org.apache.maven.plugins.maven-failsafe-plugin", version.ref = "org-apache-maven-plugins_maven-failsafe-plugin"}
org-apache-maven-plugins_maven-help-plugin = {id = "org.apache.maven.plugins.maven-help-plugin", version.ref = "org-apache-maven-plugins_maven-help-plugin"}
org-apache-maven-plugins_maven-install-plugin = {id = "org.apache.maven.plugins.maven-install-plugin", version.ref = "org-apache-maven-plugins_maven-install-plugin"}
org-apache-maven-plugins_maven-invoker-plugin = {id = "org.apache.maven.plugins.maven-invoker-plugin", version.ref = "org-apache-maven-plugins_maven-invoker-plugin"}
org-apache-maven-plugins_maven-gpg-plugin = {id = "org.apache.maven.plugins.maven-gpg-plugin", version.ref = "org-apache-maven-plugins_maven-gpg-plugin"}
# Spring
org-springframework-boot_spring-boot-maven-plugin = {id = "org.springframework.boot.spring-boot-maven-plugin", version.ref = "org-springframework-boot_spring-boot-maven-plugin"}
# Codehaus
org-codehaus-mojo_build-helper-maven-plugin = {id = "org.codehaus.mojo.build-helper-maven-plugin", version.ref = "org-codehaus-mojo_build-helper-maven-plugin"}
org-codehaus-mojo_versions-maven-plugin = {id = "org.codehaus.mojo.versions-maven-plugin", version.ref = "org-codehaus-mojo_versions-maven-plugin"}
org-codehaus-mojo_xml-maven-plugin = {id = "org.codehaus.mojo.xml-maven-plugin", version.ref = "org-codehaus-mojo_xml-maven-plugin"}
# Github
io-github-git-commit-id_git-commit-id-maven-plugin = {id = "io.github.git-commit-id.git-commit-id-maven-plugin", version.ref = "io-github-git-commit-id_git-commit-id-maven-plugin"}
com-github-github_site-maven-plugin = {id = "com.github.github.site-maven-plugin", version.ref = "com-github-github_site-maven-plugin"}
# Other
org-cyclonedx_cyclonedx-maven-plugin = {id = "org.cyclonedx.cyclonedx-maven-plugin", version.ref = "org-cyclonedx_cyclonedx-maven-plugin"}
org-flywaydb_flyway-maven-plugin = {id = "org.flywaydb.flyway-maven-plugin", version.ref = "org-flywaydb_flyway-maven-plugin"}
org-jooq_jooq-codegen-maven = {id = "org.jooq.jooq-codegen-maven", version.ref = "org-jooq_jooq-codegen-maven"}
org-jetbrains-kotlin_kotlin-maven-plugin = {id = "org.jetbrains.kotlin.kotlin-maven-plugin", version.ref = "org-jetbrains-kotlin_kotlin-maven-plugin"}
org-liquibase_liquibase-maven-plugin = {id = "org.liquibase.liquibase-maven-plugin", version.ref = "org-liquibase_liquibase-maven-plugin"}
org-graalvm-buildtools_native-maven-plugin = {id = "org.graalvm.buildtools.native-maven-plugin", version.ref = "org-graalvm-buildtools_native-maven-plugin"}
