import org.gradle.api.artifacts.VersionCatalogsExtension

plugins {
    id 'org.zero.conventions.java17-library'
}

/*
 * Catalog 访问。
 * 作用：从当前 `libs` catalog 解析 Boot 3 场景下的额外适配器坐标。
 */
def libsCatalog = extensions.getByType(VersionCatalogsExtension).named('libs')

/*
 * 依赖布局。
 * 作用：在根平台基础上叠加 Spring 与 Jakarta 高版本 BOM，隔离新生态依赖面。
 */
dependencies {
    implementation(platform(libs.org.springframework.spring.framework.bom))
    implementation(platform(libs.org.springframework.boot.spring.boot.dependencies))
    implementation(platform(libs.org.springframework.cloud.spring.cloud.dependencies))
    implementation(platform(libs.com.alibaba.cloud.spring.cloud.alibaba.dependencies))
    implementation(platform(libs.jakarta.platform.jakarta.jakartaee.bom))
    compileOnly(project(':core-base'))
    compileOnly(project(':core-jakarta'))
    compileOnly(project(':common-data'))
    implementation('org.springframework:spring-web')
    implementation('org.springframework:spring-webmvc')
    implementation('org.springframework.boot:spring-boot')
    implementation('org.springframework.boot:spring-boot-autoconfigure')
    implementation(libsCatalog.findLibrary('com-alibaba-csp_sentinel-spring-webmvc-6x-adapter').get().get())
    implementation('jakarta.servlet:jakarta.servlet-api')
    implementation('jakarta.validation:jakarta.validation-api')
    implementation('io.github.openfeign:feign-core')
    implementation('org.slf4j:slf4j-api')

    /*
     * Lombok 编译支持。
     * 作用：仅在编译期保留注解处理能力。
     */
    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
    testCompileOnly(libs.org.projectlombok.lombok)
    testAnnotationProcessor(libs.org.projectlombok.lombok)
    testImplementation(project(':core-base')) {
        transitive = false
    }
    testImplementation(project(':core-jakarta')) {
        transitive = false
    }
    testImplementation(project(':common-data')) {
        transitive = false
    }
    testImplementation('com.fasterxml.jackson.core:jackson-databind')
    testImplementation('com.fasterxml.jackson.datatype:jackson-datatype-jsr310')
}

description = 'common-core::spring-boot3'
